# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Thanks for contributing! Here are some tips you can follow to help us incorporate your contribution quickly and easily:
#1. If this is your first time, please read our contributor guidelines:
#  - https://streampipes.apache.org/getinvolved.html
#  - https://cwiki.apache.org/confluence/display/STREAMPIPES/Getting+Started
#2. Make sure the PR title is formatted like: `[#<GitHub issue id>] PR title ...`
# 3. If the PR is unfinished, add '[WIP]' in your PR title, e.g., `[WIP][#<GitHub issue id>] PR title ...`.
# 4. Please write your PR title to summarize what this PR proposes/fixes.
# 5. Link the PR to the corresponding GitHub issue (if present) in the `Development` section in the right menu bar.
# 6. Be sure to keep the PR description updated to reflect all changes.
# 7. If possible, provide a concise example to reproduce the issue for a faster review.
# 8. Make sure tests pass via `mvn clean install`.
# 9. (Optional) If the contribution is large, please file an Apache ICLA
#    - http://apache.org/licenses/icla.pdf

---
name: Fast Track (Committers only)
description: (Committers only) Quick and informal way to create issues/tasks
labels: [ ]
body:
  - type: textarea
    attributes:
      label: Purpose
      description: Please clarify what changes you are proposing and describe how those changes will address the issue. Furthermore, describe potential consequences the changes might have.
  - type: textarea
    attributes:
      label: Remarks
      description: Is there anything left we need to pay attention on? Are there some references that might be important? E.g. links to Confluence, or discussions on the mailing list or GitHub.
  - type: dropdown
    attributes:
      label: Breaking Changes
      description: PR introduces (a) breaking change(s)
      options:
        - yes
        - no
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Deprecations
      description: PR introduces (a) deprecation(s)
      options:
        - yes
        - no
    validations:
      required: true
