# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if eq .Values.preferredBroker "kafka" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.external.zookeeper.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.external.zookeeper.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.external.zookeeper.appName }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: {{ .Values.external.zookeeper.persistence.pvName }}
          persistentVolumeClaim:
            claimName: {{ .Values.external.zookeeper.persistence.claimName }}
      containers:
        #TODO: wurstmeister/zookeeper:latest is running ZK 3.4.13. Once this
        #      changes, the mount path needs to be adapted
        - name: {{ .Values.external.zookeeper.appName }}
          image: fogsyio/zookeeper:{{ .Values.external.zookeeper.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.external.zookeeper.port }}
          volumeMounts:
            - mountPath: "/opt/zookeeper-{{ .Values.external.zookeeper.version }}/data"
              name: {{ .Values.external.zookeeper.persistence.pvName }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - echo ruok | nc localhost {{ .Values.external.zookeeper.port }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: {{ .Values.periodSeconds }}
            failureThreshold: {{ .Values.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - echo ruok | nc localhost {{ .Values.external.zookeeper.port }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: {{ .Values.periodSeconds }}
            failureThreshold: {{ .Values.failureThreshold }}
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - echo ruok | nc localhost {{ .Values.external.zookeeper.port }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: {{ .Values.periodSeconds }}
            failureThreshold: {{ .Values.failureThreshold }}
{{- end }}