#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

changelog:
  exclude:
    labels:
      - no release note
  categories:
    - title: StreamPipes Connect 🔌
      labels:
          - connect
    - title: StreamPipes Core 🥑
      labels:
        - backend
    - title: StreamPipes Pipeline Elements ⚙️
      labels:
        - pipeline elements
    - title: StreamPipes Python 🐍
      labels:
        - python
    - title: StreamPipes UI 🖥️
      labels:
        - ui
    - title: Bug fixes 🧰
      labels:
        - bug
    - title: Breaking changes 💣
      labels:
        - breaking change
    - title: Deprecation ⚠️
      labels:
        - deprecation
    - title: Documentation & Website 📚
      labels:
        - documentation
        - website
    - title: Dependency Updates 📦
      labels:
        - dependencies
