<?xml version="1.0" encoding="UTF-8"?>

<!--
~ Licensed to the Apache Software Foundation (ASF) under one or more
~ contributor license agreements.  See the NOTICE file distributed with
~ this work for additional information regarding copyright ownership.
~ The ASF licenses this file to You under the Apache License, Version 2.0
~ (the "License"); you may not use this file except in compliance with
~ the License.  You may obtain a copy of the License at
~
~    http://www.apache.org/licenses/LICENSE-2.0
~
~ Unless required by applicable law or agreed to in writing, software
~ distributed under the License is distributed on an "AS IS" BASIS,
~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
~ See the License for the specific language governing permissions and
~ limitations under the License.
~
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache</groupId>
        <artifactId>apache</artifactId>
        <version>37</version>
    </parent>

    <groupId>org.apache.streampipes</groupId>
    <artifactId>streampipes-parent</artifactId>
    <version>0.99.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Apache StreamPipes</name>
    <description>A self-service (Industrial) IoT toolbox to enable non-technical users to connect, analyze and explore
        IoT data streams.
    </description>
    <url>https://streampipes.apache.org</url>

    <properties>
        <plc4x.version>0.13.1</plc4x.version>
        <!-- Maven settings & dependencies -->
        <apache-rat-plugin.version>0.16.1</apache-rat-plugin.version>
        <checksum-maven-plugin.version>1.11</checksum-maven-plugin.version>
        <checkstyle.version>10.17.0</checkstyle.version>
        <extra-enforcer-rules.version>1.8.0</extra-enforcer-rules.version>
        <formatter-maven-plugin.version>2.23.0</formatter-maven-plugin.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <maven-checkstyle-plugin.version>3.3.1</maven-checkstyle-plugin.version>
        <maven-shade-plugin.version>3.6.0</maven-shade-plugin.version>

        <minimalMavenBuildVersion>3.8</minimalMavenBuildVersion>
        <typescript-generator-maven-plugin.version>3.2.1263</typescript-generator-maven-plugin.version>
        <spotless.version>2.43.0</spotless.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <dependency.locations.enabled>false</dependency.locations.enabled>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>4.0.2</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.apache.streampipes</groupId>
                <artifactId>streampipes-bom</artifactId>
                <version>0.99.0-SNAPSHOT</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>archetypes/streampipes-archetype-extensions-jvm</module>
        <module>streampipes-client</module>
        <module>streampipes-client-api</module>
        <module>streampipes-commons</module>
        <module>streampipes-connect-management</module>
        <module>streampipes-connect-shared</module>
        <module>streampipes-extensions-api</module>
        <module>streampipes-extensions-management</module>
        <module>streampipes-data-explorer</module>
        <module>streampipes-data-explorer-api</module>
        <module>streampipes-data-explorer-export</module>
        <module>streampipes-data-explorer-influx</module>
        <module>streampipes-data-explorer-iotdb</module>
        <module>streampipes-data-explorer-management</module>
        <module>streampipes-data-export</module>
        <module>streampipes-dataformat</module>
        <module>streampipes-extensions</module>
        <module>streampipes-integration-tests</module>
        <module>streampipes-mail</module>
        <module>streampipes-maven-plugin</module>
        <module>streampipes-measurement-units</module>
        <module>streampipes-messaging-kafka</module>
        <module>streampipes-messaging</module>
        <module>streampipes-messaging-jms</module>
        <module>streampipes-messaging-mqtt</module>
        <module>streampipes-messaging-nats</module>
        <module>streampipes-messaging-pulsar</module>
        <module>streampipes-model</module>
        <module>streampipes-model-client</module>
        <module>streampipes-model-shared</module>
        <module>streampipes-resource-management</module>
        <module>streampipes-load-balancer</module>
        <module>streampipes-pipeline-management</module>
        <module>streampipes-rest-extensions</module>
        <module>streampipes-rest</module>
        <module>streampipes-rest-core-base</module>
        <module>streampipes-rest-shared</module>
        <module>streampipes-sdk</module>
        <module>streampipes-sdk-bundle</module>
        <module>streampipes-security-jwt</module>
        <module>streampipes-serializers-json</module>
        <module>streampipes-service-base</module>
        <module>streampipes-service-core</module>
        <module>streampipes-service-core-minimal</module>
        <module>streampipes-service-discovery</module>
        <module>streampipes-service-discovery-api</module>
        <module>streampipes-service-extensions</module>
        <module>streampipes-storage-api</module>
        <module>streampipes-storage-couchdb</module>
        <module>streampipes-storage-management</module>
        <module>streampipes-test-utils</module>
        <module>streampipes-test-utils-executors</module>
        <module>streampipes-user-management</module>
        <module>streampipes-vocabulary</module>
        <module>streampipes-wrapper</module>
        <module>streampipes-wrapper-distributed</module>
        <module>streampipes-wrapper-kafka-streams</module>
        <module>streampipes-wrapper-siddhi</module>
        <module>streampipes-wrapper-standalone</module>
        <module>streampipes-connect-transformer-api</module>
        <module>streampipes-connect-transformer-groovy</module>
        <module>streampipes-connect-transformer-js</module>
        <module>streampipes-health-monitoring</module>
        <module>streampipes-bom</module>
    </modules>

    <profiles>
        <profile>
            <id>apache-release</id>
            <build>
                <plugins>
                    <!--
                        Create MD5 and SHA512 checksum files for the release artifacts.
                    -->
                    <plugin>
                        <groupId>net.nicoulaj.maven.plugins</groupId>
                        <artifactId>checksum-maven-plugin</artifactId>
                        <version>${checksum-maven-plugin.version}</version>
                        <inherited>false</inherited>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>files</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <algorithms>
                                <algorithm>SHA-512</algorithm>
                            </algorithms>
                            <fileSets>
                                <fileSet>
                                    <directory>${project.build.directory}</directory>
                                    <includes>
                                        <include>apache-streampipes-${project.version}-source-release.zip
                                        </include>
                                    </includes>
                                </fileSet>
                            </fileSets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <failOnError>false</failOnError>
                                    <additionalJOption>-Xdoclint:none</additionalJOption>
                                    <doclint>none</doclint>
                                    <additionalJOption>-Xdoclint:none</additionalJOption>
                                    <source>17</source>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <!-- Build Settings -->
    <build>

        <!-- Plugin Management -->

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>cz.habarta.typescript-generator</groupId>
                    <artifactId>typescript-generator-maven-plugin</artifactId>
                    <version>${typescript-generator-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>net.revelc.code.formatter</groupId>
                    <artifactId>formatter-maven-plugin</artifactId>
                    <version>${formatter-maven-plugin.version}</version>
                    <configuration>
                        <lineEnding>LF</lineEnding>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <release>17</release>
                        <encoding>UTF-8</encoding>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${maven-shade-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <configuration>
                        <useReleaseProfile>true</useReleaseProfile>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <releaseProfiles>apache-release</releaseProfiles>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>source-release-assembly</id>
                            <configuration>
                                <finalName>apache-streampipes-${project.version}</finalName>
                                <descriptors>
                                    <descriptor>tools/maven/assembly.xml</descriptor>
                                </descriptors>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${maven-checkstyle-plugin.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.puppycrawl.tools</groupId>
                            <artifactId>checkstyle</artifactId>
                            <version>${checkstyle.version}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>validate</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <suppressionsLocation>tools/maven/suppressions.xml</suppressionsLocation>
                        <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        <configLocation>tools/maven/checkstyle.xml</configLocation>
                        <encoding>UTF-8</encoding>
                        <logViolationsToConsole>true</logViolationsToConsole>
                        <failOnViolation>true</failOnViolation>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>


        <!-- Plugins -->


        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <inherited>false</inherited>
                        <id>installer-files</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <runOnlyAtExecutionRoot>true</runOnlyAtExecutionRoot>
                            <finalName>apache-streampipes-${project.version}-installer</finalName>
                            <descriptors>
                                <descriptor>${project.basedir}/tools/maven/installer.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>check-at-least-java-25</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>1.25.0</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                    <!-- Ensure we're not mixing dependency versions -->
                    <execution>
                        <id>enforce-version-convergence</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <dependencyConvergence />
                            </rules>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>extra-enforcer-rules</artifactId>
                        <version>${extra-enforcer-rules.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <failOnError>false</failOnError>
                            <failOnWarnings>false</failOnWarnings>
                            <additionalJOption>-Xdoclint:none</additionalJOption>
                            <doclint>none</doclint>
                            <additionalJOption>-Xdoclint:none</additionalJOption>
                            <release>11</release>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <failOnWarnings>false</failOnWarnings>
                    <failOnError>false</failOnError>
                    <source>25</source>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless.version}</version>
                <configuration>
                    <skip>true</skip>
                    <java>
                        <importOrder>
                            <order>org.apache.streampipes,,jakarta,javax,java,scala,\#</order>
                        </importOrder>
                        <eclipse>
                            <file>tools/maven/streampipes-code-formatter.xml</file>
                        </eclipse>
                        <licenseHeader>
                            <file>tools/maven/checkstyle-header.txt</file>
                        </licenseHeader>
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <id>spotless-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>validate</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.rat</groupId>
                <artifactId>apache-rat-plugin</artifactId>
                <executions>
                    <execution>
                        <id>license-check</id>
                        <inherited>false</inherited>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludeSubProjects>false</excludeSubProjects>
                    <useMavenDefaultExcludes>true</useMavenDefaultExcludes>
                    <consoleOutput>true</consoleOutput>
                    <excludes>
                        <!-- Git related files -->
                        <exclude>**/.git/**</exclude>
                        <exclude>**/.gitignore</exclude>
                        <exclude>**/.gitkeep</exclude>
                        <exclude>**/.spignore</exclude>

                        <!-- License Files for other licenses -->
                        <exclude>**/UNLICENSE</exclude>

                        <!-- Maven related files -->
                        <exclude>**/target/**</exclude>
                        <exclude>target/**</exclude>

                        <!-- Eclipse related files -->
                        <exclude>**/.project</exclude>
                        <exclude>**/.settings/**</exclude>
                        <exclude>**/.classpath</exclude>
                        <exclude>**/.factorypath</exclude>

                        <!-- IntelliJ related files -->
                        <exclude>**/.idea/**</exclude>
                        <exclude>**/*.iml</exclude>

                        <!-- JSON doesn't like comments -->
                        <exclude>**/*.json</exclude>
                        <exclude>**/*.jsonld</exclude>
                        <exclude>**/*.txt</exclude>

                        <!-- CSV also doesn't like comments -->
                        <exclude>**/*.csv</exclude>

                        <!-- Jupyter Notebooks as well -->
                        <exclude>**/*.ipynb</exclude>

                        <!-- Ignore SVG files -->
                        <exclude>**/*.svg</exclude>

                        <exclude>**/system</exclude>

                        <!-- Test files -->
                        <exclude>streampipes-code-generation/src/main/resources/pom</exclude>
                        <exclude>streampipes-code-generation/src/main/resources/web</exclude>
                        <exclude>streampipes-code-generation/src/test/resources/*_java</exclude>
                        <exclude>streampipes-code-generation/src/test/resources/expected_pom_xml</exclude>
                        <exclude>streampipes-code-generation/src/test/resources/expected_web_xml</exclude>

                        <!-- Archetype resources should not have ASF license header -->
                        <exclude>archetypes/streampipes-archetype-pe-processors-jvm/src/main/resources/**</exclude>
                        <exclude>archetypes/streampipes-archetype-pe-sinks-jvm/src/main/resources/**</exclude>

                        <!-- External files -->
                        <exclude>
                            streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/processor/revgeocoder/geocode/**
                        </exclude>

                        <!-- External vocabularies -->
                        <exclude>streampipes-measurement-units/src/main/java/com/github/jqudt/**</exclude>

                        <!-- Exclude some UI files which we need to check in more detail -->
                        <exclude>ui/src/assets/img/svg/**</exclude>

                        <!-- Exclude .angular folder -->
                        <exclude>ui/.angular/**</exclude>

                        <!-- Exclude disclaimer and notice files -->
                        <exclude>DISCLAIMER</exclude>
                        <exclude>NOTICE-binary</exclude>

                        <!-- Exclude license files in license folder -->
                        <exclude>licenses/BSD_3-Clause</exclude>
                        <exclude>licenses/CDDL_1.1</exclude>
                        <exclude>licenses/CDDL_1.0</exclude>
                        <exclude>licenses/Eclipse_Distribution_License_v1.0</exclude>
                        <exclude>licenses/EPL_2.0</exclude>
                        <exclude>licenses/CDDL_LICENSE_1.1</exclude>
                        <exclude>licenses/EPL_1.0</exclude>
                        <exclude>licenses/BSD_2-Clause</exclude>

                        <!-- Exclude Python env -->
                        <exclude>**/venv/**</exclude>
                        <exclude>**/.pytest_cache/**</exclude>
                        <exclude>.ruff_cache/**</exclude>
                        <exclude>.mypy_cache/**</exclude>
                        <exclude>**/site/**</exclude>
                        <exclude>**/.mypy_cache/**</exclude>
                        <exclude>**/poetry.lock</exclude>

                        <!-- Exclude Husky which defines its own gitignore and is not detected by rat -->
                        <exclude>ui/.husky/**</exclude>

                        <!-- Exclude GO -->
                        <exclude>**/go.sum</exclude>



          <!-- Resource files for Integration Test-->
          <exclude>streampipes-integration-tests/src/test/resources/mosquitto.crt</exclude>
          <exclude>streampipes-integration-tests/src/test/resources/mosquitto copy.conf</exclude>
          <exclude>streampipes-integration-tests/src/test/resources/mosquitto.key</exclude>
          <exclude>streampipes-integration-tests/src/test/resources/passwd</exclude>


                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>17</release>
                    <encoding>UTF-8</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
                <configuration>
                    <logViolationsToConsole>false</logViolationsToConsole>
                    <failOnViolation>false</failOnViolation>
                </configuration>
                <inherited>false</inherited>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-opens java.base/java.lang=ALL-UNNAMED
                        --add-opens java.base/java.util=ALL-UNNAMED
                        --add-opens java.base/java.base=ALL-UNNAMED
                        --add-opens java.base/java.util.stream=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <scm>
        <developerConnection>scm:git:ssh://git@github.com/apache/streampipes.git</developerConnection>
        <connection>scm:git:ssh://git@github.com/apache/streampipes.git</connection>
        <url>https://github.com/apache/streampipes</url>
      <tag>HEAD</tag>
  </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/apache/streampipes/issues</url>
    </issueManagement>

    <mailingLists>
        <mailingList>
            <name>Apache StreamPipes Developer List</name>
            <subscribe>mailto:dev-subscribe@streampipes.apache.org</subscribe>
            <unsubscribe>mailto:dev-unsubscribe@streampipes.apache.org</unsubscribe>
            <post>mailto:dev@streampipes.apache.org</post>
            <archive>http://mail-archives.apache.org/mod_mbox/streampipes-dev/</archive>
        </mailingList>
        <mailingList>
            <name>Apache StreamPipes User List</name>
            <subscribe>mailto:users-subscribe@streampipes.apache.org</subscribe>
            <unsubscribe>mailto:users-unsubscribe@streampipes.apache.org</unsubscribe>
            <post>mailto:users@streampipes.apache.org</post>
            <archive>http://mail-archives.apache.org/mod_mbox/streampipes-users/</archive>
        </mailingList>
        <mailingList>
            <name>Apache StreamPipes Commits List</name>
            <subscribe>mailto:commits-subscribe@streampipes.apache.org</subscribe>
            <unsubscribe>mailto:commits-unsubscribe@streampipes.apache.org</unsubscribe>
            <post>mailto:commits@streampipes.apache.org</post>
            <archive>http://mail-archives.apache.org/mod_mbox/streampipes-commits/</archive>
        </mailingList>
        <mailingList>
            <name>Apache StreamPipes Issue Notifications List</name>
            <subscribe>mailto:issues-subscribe@streampipes.apache.org</subscribe>
            <unsubscribe>mailto:issues-unsubscribe@streampipes.apache.org</unsubscribe>
            <post>mailto:issues@streampipes.apache.org</post>
            <archive>http://mail-archives.apache.org/mod_mbox/streampipes-issues/</archive>
        </mailingList>
    </mailingLists>

</project>
