#!/bin/bash

if [[ $1 = "start" ]];
then
	echo 'Start StreamPipes'
fi

if [[ $1 = "stop" ]];
then
	echo 'Stop StreamPipes'
fi

if [[ $1 = "clean" ]];
then
	echo 'Clean StreamPipes'
fi

if [[ $1 = "service" ]];
then
	if [[ $2 = "add" ]];
	then
		echo 'Add a service'
	else

		if [[ $2 = "remove" ]];
		then

			echo 'Remove a service'
		else 
			echo "streampipes service does not support " $2

		fi

	fi
fi



