FROM hypriot/rpi-java

ADD ./de.fzi.cep.sepa/semantic-epa-sources-demonstrator-adapter/0.0.2-SNAPSHOT/semanitc-epa-sources-demonstrator-adapter-0.0.2-SNAPSHOT.jar  /semantic-epa-sources-demonstrator-adapter.jar

ENTRYPOINT ["java", "-jar", "/semantic-epa-sources-demonstrator-adapter.jar"]
