# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: StreamPipes Documentation/Website issue report
description: Problems and issues with Apache StreamPipes documentation or website
labels: ["bug", "documentation", "website"]
body:
  - type: markdown
    attributes:
      value: "
        <p align='center'>
        
        <img src='https://streampipes.apache.org/img/sp-logo-color.png' alt='StreamPipes Logo' title='Apache StreamPipes Logo' width='50%' align='center'/>
        </p>
        
        <br>
        
        Thank you for taking the time to report the issue!

        We greatly appreciate the community's efforts to improve StreamPipes.

        Please note that you do not need to create an issue if you want to submit a change!

        You can open a <a href='https://github.com/apache/streampipes/pulls'>pull request</a> immediately instead.
        "

  - type: dropdown
    attributes:
      label: Where does your observation occur?
      description: Please choose whether the issue you want to report occurs on the [website](https://streampipes.apache.org/) or on the [documentation](https://streampipes.apache.org/docs/index.html).
      multiple: false
      options:
        - StreamPipes Documentation
        - StreamPipes Website

  - type: textarea
    attributes:
      label: What do you want to report?
      description: Please describe the issue you have observed.
      placeholder: >
        Please include links to the part of the documentation/website that has the problem and possibly screenshots (or even GIFs) showing
        the problem. Explain why do you think it is an issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solving the problem
      description: Do you already have an idea how this could be solved?
      placeholder: >
        Please explain how you think the documentation/website could be improved.
        Ideally, indicate where new or missing descriptions should be added and what type of information should be included.
        Sometimes the authors are not aware that some assumptions they have are not in the minds of the readers.
        Therefore, try to explain exactly what you want to see in the documentation/website and why (if applicable).
  - type: textarea
    attributes:
      label: Anything left
      description: Is there anything left you would like to add?
      placeholder: >
        How often does this problem occur? (Once? Every time? Only when certain conditions are met?)
        How urgent do you think it is that the problem be fixed?
        How did you stumble upon the problem?
        Is there any contextual information that you think is valuable?

  - type: dropdown
    attributes:
      label: Are you willing to submit a PR?
      description: >
        This is absolutely not required, but we will be happy to help you write the post especially if
        you already have a good understanding of how to implement the fix.
        StreamPipes is a community-driven project and we welcome new contributors.
        Find us [here](https://github.com/apache/streampipes/discussions/categories/q-a) or contact us on our mailing list (dev@streampipes.apache.org).
      options:
        - Yes, I am willing to submit a PR!
        - No, I don't want to submit a PR.

  - type: markdown
    attributes:
      value: ":pray: Thanks a lot for completing our form!"