# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: Fast Track (Committers only)
description: (Committers only) Quick and informal way to create issues/tasks
labels: []
body:
  - type: textarea
    attributes:
      label: Body
      description: Free text issue for committers of Apache StreamPipes to be able to add issues/tasks
  - type: dropdown
    attributes:
      label: StreamPipes Committer
      description: Committer acknowledgment.
      options:
        - I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.
    validations:
      required: true
