#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deployment_notice() {
	echo
	echo
	echo "INFO: StreamPipes $1 is now ready to be used on your system"
	echo "      Check https://streampipes.apache.org/ for information on StreamPipes"
	echo
	echo "      Go to the UI and follow the instructions to get started: http://$2/"
	echo
}

if [ -z "$1" ] || [ "$#" -lt 1 ];
then
	echo "Use 'streampipes start' to start StreamPipes, 'streampipes stop' to stop it, and 'streampipes clean' to remove streampipes."
	exit 1
fi

if [ $1 = "start" ];
then

echo ' _______ __                              ______ __                    '
echo '|     __|  |_.----.-----.---.-.--------.|   __ \__|.-----.-----.-----.'
echo '|__     |   _|   _|  -__|  _  |        ||    __/  ||  _  |  -__|__ --|'
echo '|_______|____|__| |_____|___._|__|__|__||___|  |__||   __|_____|_____|'
echo '                                                   |__|'
echo ''
echo 'Welcome to StreamPipes!'
echo ''

if [ ! -f ./docker-compose.yml ];
	then
		echo '';
		echo ''
		echo 'StreamPipes can be started in two different setups:'
		echo ''
		PS3='Which StreamPipes version should be installed? '
		options=("StreamPipes Lite (few pipeline elements, needs less memory)" "StreamPipes Full (more pipeline elements, requires > 16 GB RAM)")
		select opt in "${options[@]}"
		do
		if [ -z "${opt}" ];
			then
				echo "Wrong input, select one of the options";
			else
				case $opt in
			"StreamPipes Lite (few pipeline elements, needs less memory)")
				version="Lite"
				;;
			"StreamPipes Full (more pipeline elements, requires > 16 GB RAM)")
				version="Full"
				;;
				esac
				break

			fi
		done

		echo "Selected StreamPipes option: $version";

		echo "Configuring StreamPipes $version"
		if [ $version == "Lite" ];
		then
			cp ../templates/docker-compose.lite.yml ./docker-compose.yml
		else
			cp ../templates/docker-compose.full.yml ./docker-compose.yml
		fi

		cp ../templates/.env ./.env

	fi

	docker-compose pull
	docker-compose up -d

	if [ $? -eq 0 ]; then
		SP_VERSION=`grep SP_VERSION ".env" | awk -F= '{print $2}'`
		deployment_notice $SP_VERSION "localhost"
	else
		echo "ERROR: There was a problem while starting StreamPipes"
	fi

else
	if [ $1 = "stop" ] || [ $1 = "clean" ];
	then
	    if [ $1 = "stop" ];
		then
			docker-compose down
			echo "StreamPipes successfully stopped"
		fi

		if [ $1 = "clean" ];
		then
		    yes Y | docker-compose down -v
			rm ./docker-compose.yml
			rm ./.env
			echo "All StreamPipes System informations were deleted. The system can now be installed again."
		fi

	else
		echo "Command '$1' is not supported! Use 'streampipes start' to start StreamPipes, 'streampipes stop' to stop it, and 'streampipes clean' to remove streampipes."
	fi

fi
