<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.apache.streampipes</groupId>
    <artifactId>streampipes-bom</artifactId>
    <version>0.99.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <apache-sis-referencing.version>1.2</apache-sis-referencing.version>
        <antlr4.version>4.11.1</antlr4.version>
        <bcprov-jdk18on.version>1.78.1</bcprov-jdk18on.version>
        <boofcv.version>1.1.0</boofcv.version>
        <classindex.version>3.9</classindex.version>
        <commons-collections.version>3.2.2</commons-collections.version>
        <commoms-collection4.version>4.4</commoms-collection4.version>
        <commons-compress.version>1.27.1</commons-compress.version>
        <commons-configuration2.version>2.12.0</commons-configuration2.version>
        <commons-csv.version>1.14.1</commons-csv.version>
        <commons-io.version>2.17.0</commons-io.version>
        <commons-jexl.version>3.4.0</commons-jexl.version>
        <commons-text.version>1.12.0</commons-text.version>
        <ditto-client.version>1.0.0</ditto-client.version>
        <error-prone.version>2.10.0</error-prone.version>
        <google-maps-services.version>2.2.0</google-maps-services.version>
        <graalvm.js.version>25.0.0</graalvm.js.version>
        <groovy.version>5.0.3</groovy.version>
        <grpc.version>1.76.0</grpc.version>
        <guava.version>33.5.0-jre</guava.version>
        <hadoop.version>3.4.1</hadoop.version>
        <hadoop-mapreduce-client-core.version>3.4.1</hadoop-mapreduce-client-core.version>
        <jgrapht.version>1.5.1</jgrapht.version>
        <jjwt.version>0.11.2</jjwt.version>
        <lightcouch.version>0.2.0</lightcouch.version>
        <eclipse.milo.version>0.6.16</eclipse.milo.version>
        <fogsy-qudt.version>1.0</fogsy-qudt.version>
        <httpclient.version>4.5.13</httpclient.version>
        <httpcore.version>4.4.9</httpcore.version>
        <influxdb.version>2.24</influxdb.version>
        <inlong.version>1.13.0</inlong.version>
        <iotdb.version>1.3.0</iotdb.version>
        <jts-core.version>1.19.0</jts-core.version>
        <milvus-sdk-java.version>2.5.10</milvus-sdk-java.version>
        <mqtt-client.version>1.3.0</mqtt-client.version>
        <nats.version>2.19.1</nats.version>
        <okhttp.version>3.13.1</okhttp.version>
        <opencsv.version>5.9</opencsv.version>
        <opennlp.version>2.3.1</opennlp.version>
        <parquet.version>1.16.0</parquet.version>
        <protobuf.version>4.28.2</protobuf.version>
        <qdrant-java-client.version>1.14.0</qdrant-java-client.version>
        <plc4x.version>0.13.1</plc4x.version>

        <!-- needs to be lower than 4.x.x, see https://github.com/apache/streampipes/issues/1495 -->
        <rdf4j.version>3.7.7</rdf4j.version>

        <rendersnake.version>1.9.0</rendersnake.version>
        <rocketmq.version>5.0.2</rocketmq.version>

        <jsrosbridge.version>0.2.0</jsrosbridge.version>


        <s3.version>2.25.14</s3.version>


        <siddhi.version>5.1.27</siddhi.version>
        <simple-java-mail.version>8.10.0</simple-java-mail.version>
        <slack-api.version>1.4.0</slack-api.version>
        <springdoc.version>3.0.1</springdoc.version>
        <swagger.version>2.2.42</swagger.version>
        <tsfile.version>1.1.0</tsfile.version>
        <type-parser.version>0.8.1</type-parser.version>
        <xz.version>1.10</xz.version>

        <!-- streampipes-maven-plugin -->
        <file-management.version>3.1.0</file-management.version>
        <maven.version>3.8.7</maven.version>
        <maven-plugin-annotations.version>3.13.0</maven-plugin-annotations.version>
        <plexus-component-annotations.version>2.2.0</plexus-component-annotations.version>
        <plexus-interactivity-api.version>1.1</plexus-interactivity-api.version>
        <plexus-utils.version>4.0.0</plexus-utils.version>


        <!-- dependency convergence -->
        <javassist.version>3.30.1-GA</javassist.version>
        <woodstox.version>7.0.0</woodstox.version>
        <istack-runtime.version>4.1.2</istack-runtime.version>
        <javax.xml.bind.version>2.3.1</javax.xml.bind.version>
        <jaxb-runtime.version>2.3.9</jaxb-runtime.version>
        <jakarta-xml-bind-api.version>4.0.0</jakarta-xml-bind-api.version>
        <java-websocket.version>1.6.0</java-websocket.version>
        <javax-websocket-api.version>1.1</javax-websocket-api.version>
        <jetbrains.version>16.0.3</jetbrains.version>

        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>${javax.xml.bind.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.websocket</groupId>
                <artifactId>javax.websocket-api</artifactId>
                <version>${javax-websocket-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${jaxb-runtime.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-collections</groupId>
                <artifactId>commons-collections</artifactId>
                <version>${commons-collections.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-jexl3</artifactId>
                <version>${commons-jexl.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-csv</artifactId>
                <version>${commons-csv.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons-compress.version}</version>
            </dependency>
            <dependency>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-runtime</artifactId>
                <version>${antlr4.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons-text.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.woodstox</groupId>
                <artifactId>woodstox-core</artifactId>
                <version>${woodstox.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.drapostolos</groupId>
                <artifactId>type-parser</artifactId>
                <version>${type-parser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.errorprone</groupId>
                <artifactId>error_prone_annotations</artifactId>
                <version>${error-prone.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sun.istack</groupId>
                <artifactId>istack-commons-runtime</artifactId>
                <version>${istack-runtime.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commoms-collection4.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.maps</groupId>
                <artifactId>google-maps-services</artifactId>
                <version>${google-maps-services.version}</version>
            </dependency>
            <dependency>
                <groupId>com.hivemq</groupId>
                <artifactId>hivemq-mqtt-client</artifactId>
                <version>${mqtt-client.version}</version>
            </dependency>
            <dependency>
                <groupId>com.opencsv</groupId>
                <artifactId>opencsv</artifactId>
                <version>${opencsv.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <dependency>
                <groupId>com.ullink.slack</groupId>
                <artifactId>simpleslackapi</artifactId>
                <version>${slack-api.version}</version>
            </dependency>
            <dependency>
                <groupId>edu.wpi.rail</groupId>
                <artifactId>jrosbridge</artifactId>
                <version>${jsrosbridge.version}</version>
            </dependency>
            <dependency>
                <groupId>io.fogsy</groupId>
                <artifactId>qudt</artifactId>
                <version>${fogsy-qudt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-context</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-stub</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-protobuf</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-netty-shaded</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.milvus</groupId>
                <artifactId>milvus-sdk-java</artifactId>
                <version>${milvus-sdk-java.version}</version>
            </dependency>
            <dependency>
                <groupId>io.qdrant</groupId>
                <artifactId>client</artifactId>
                <version>${qdrant-java-client.version}</version>
            </dependency>
            <dependency>
                <groupId>io.nats</groupId>
                <artifactId>jnats</artifactId>
                <version>${nats.version}</version>
            </dependency>
            <dependency>
                <groupId>io.siddhi</groupId>
                <artifactId>siddhi-annotations</artifactId>
                <version>${siddhi.version}</version>
            </dependency>
            <dependency>
                <groupId>io.siddhi</groupId>
                <artifactId>siddhi-core</artifactId>
                <version>${siddhi.version}</version>
            </dependency>
            <dependency>
                <groupId>io.siddhi</groupId>
                <artifactId>siddhi-query-api</artifactId>
                <version>${siddhi.version}</version>
            </dependency>
            <dependency>
                <groupId>io.siddhi</groupId>
                <artifactId>siddhi-query-compiler</artifactId>
                <version>${siddhi.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-jaxrs2-jakarta</artifactId>
                <version>${swagger.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-configuration2</artifactId>
                <version>${commons-configuration2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.groovy</groupId>
                <artifactId>groovy</artifactId>
                <version>${groovy.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>fluent-hc</artifactId>
                <version>${httpclient.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>${httpclient.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpcore</artifactId>
                <version>${httpcore.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.inlong</groupId>
                <artifactId>tubemq-client</artifactId>
                <version>${inlong.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.iotdb</groupId>
                <artifactId>iotdb-session</artifactId>
                <version>${iotdb.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-common</artifactId>
                <version>${hadoop.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-http</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-io</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-util</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-handler</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-transport</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.dropwizard.metrics</groupId>
                        <artifactId>metrics-core</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>ch.qos.reload4j</groupId>
                        <artifactId>reload4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-transport-native-epoll</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.codehaus.woodstox</groupId>
                        <artifactId>stax2-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.xerial.snappy</groupId>
                        <artifactId>snappy-java</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.avro</groupId>
                        <artifactId>avro</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>commons-net</groupId>
                        <artifactId>commons-net</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.github.luben</groupId>
                        <artifactId>zstd-jni</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-mapreduce-client-core</artifactId>
                <version>${hadoop-mapreduce-client-core.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-http</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-io</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-util</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.sun.jersey.contribs</groupId>
                        <artifactId>jersey-guice</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-all</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.avro</groupId>
                        <artifactId>avro</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.google.inject</groupId>
                        <artifactId>guice</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.opennlp</groupId>
                <artifactId>opennlp-tools</artifactId>
                <version>${opennlp.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.parquet</groupId>
                <artifactId>parquet-avro</artifactId>
                <version>${parquet.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.xerial.snappy</groupId>
                        <artifactId>snappy-java</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.avro</groupId>
                        <artifactId>avro</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.github.luben</groupId>
                        <artifactId>zstd-jni</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.plc4x</groupId>
                <artifactId>plc4j-api</artifactId>
                <version>${plc4x.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.plc4x</groupId>
                <artifactId>plc4j-spi</artifactId>
                <version>${plc4x.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.plc4x</groupId>
                <artifactId>plc4j-driver-all</artifactId>
                <version>${plc4x.version}</version>
                <type>pom</type>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.plc4x</groupId>
                        <artifactId>plc4j-driver-firmata</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.plc4x</groupId>
                        <artifactId>plc4j-driver-opcua</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.plc4x</groupId>
                        <artifactId>plc4j-driver-c-bus</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.plc4x</groupId>
                <artifactId>plc4j-connection-cache</artifactId>
                <version>${plc4x.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-client-java</artifactId>
                <version>${rocketmq.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tsfile</groupId>
                <artifactId>tsfile</artifactId>
                <version>${tsfile.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.github.luben</groupId>
                        <artifactId>zstd-jni</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.xerial.snappy</groupId>
                        <artifactId>snappy-java</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.sis.core</groupId>
                <artifactId>sis-referencing</artifactId>
                <version>${apache-sis-referencing.version}</version>
            </dependency>
            <dependency>
                <groupId>org.atteo.classindex</groupId>
                <artifactId>classindex</artifactId>
                <version>${classindex.version}</version>
            </dependency>
            <dependency>
                <groupId>org.boofcv</groupId>
                <artifactId>boofcv-core</artifactId>
                <version>${boofcv.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bcprov-jdk18on.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcutil-jdk18on</artifactId>
                <version>${bcprov-jdk18on.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.milo</groupId>
                <artifactId>sdk-client</artifactId>
                <version>${eclipse.milo.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.ditto</groupId>
                <artifactId>ditto-client</artifactId>
                <version>${ditto-client.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.milo</groupId>
                <artifactId>dictionary-reader</artifactId>
                <version>${eclipse.milo.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.rdf4j</groupId>
                <artifactId>rdf4j-rio-turtle</artifactId>
                <version>${rdf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.rdf4j</groupId>
                <artifactId>rdf4j-rio-rdfxml</artifactId>
                <version>${rdf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.graalvm.polyglot</groupId>
                <artifactId>js</artifactId>
                <version>${graalvm.js.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.graalvm.polyglot</groupId>
                <artifactId>polyglot</artifactId>
                <version>${graalvm.js.version}</version>
            </dependency>
            <dependency>
                <groupId>org.influxdb</groupId>
                <artifactId>influxdb-java</artifactId>
                <version>${influxdb.version}</version>
            </dependency>
            <dependency>
                <groupId>org.java-websocket</groupId>
                <artifactId>Java-WebSocket</artifactId>
                <version>${java-websocket.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>${jetbrains.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jgrapht</groupId>
                <artifactId>jgrapht-core</artifactId>
                <version>${jgrapht.version}</version>
            </dependency>
            <dependency>
                <groupId>org.lightcouch</groupId>
                <artifactId>lightcouch</artifactId>
                <version>${lightcouch.version}</version>
            </dependency>
            <dependency>
                <groupId>org.locationtech.jts</groupId>
                <artifactId>jts-core</artifactId>
                <version>${jts-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.rendersnake</groupId>
                <artifactId>rendersnake</artifactId>
                <version>${rendersnake.version}</version>
            </dependency>
            <dependency>
                <groupId>org.simplejavamail</groupId>
                <artifactId>simple-java-mail</artifactId>
                <version>${simple-java-mail.version}</version>
            </dependency>
            <dependency>
                <groupId>org.tukaani</groupId>
                <artifactId>xz</artifactId>
                <version>${xz.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${s3.version}</version>
            </dependency>


            <!-- required by streampipes-maven-plugin -->
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-plugin-api</artifactId>
                <version>${maven.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-core</artifactId>
                <version>${maven.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-artifact</artifactId>
                <version>${maven.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-compat</artifactId>
                <version>${maven.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-component-annotations</artifactId>
                <version>${plexus-component-annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-utils</artifactId>
                <version>${plexus-utils.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-aether-provider</artifactId>
                <version>${maven.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-model</artifactId>
                <version>${maven.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven.plugin-tools</groupId>
                <artifactId>maven-plugin-annotations</artifactId>
                <version>${maven-plugin-annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven.shared</groupId>
                <artifactId>file-management</artifactId>
                <version>${file-management.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-interactivity-api</artifactId>
                <version>${plexus-interactivity-api.version}</version>
            </dependency>


            <!--dependency convergence -->
            <dependency>
                <groupId>org.javassist</groupId>
                <artifactId>javassist</artifactId>
                <version>${javassist.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
