package org.streampipes.pe.sources.hella.sources;

import java.util.Arrays;
import java.util.List;

import org.streampipes.container.declarer.EventStreamDeclarer;
import org.streampipes.container.declarer.SemanticEventProducerDeclarer;
import org.streampipes.model.impl.graph.SepDescription;
import org.streampipes.pe.sources.hella.streams.DustParticleStream;
import org.streampipes.pe.sources.hella.streams.HumidityStream;
import org.streampipes.pe.sources.hella.streams.IrTemperatureStream;
import org.streampipes.pe.sources.hella.streams.TemperatureStream;

public class EnvironmentalDataProducer implements SemanticEventProducerDeclarer {

	@Override
	public SepDescription declareModel() {
		SepDescription sep = new SepDescription("source-environmental", "Environmental Data", "Provides streams generated by environmental sensors");
		
		return sep;
	}

	@Override
	public List<EventStreamDeclarer> getEventStreams() {
		return Arrays.asList(new DustParticleStream(), new TemperatureStream(), new IrTemperatureStream(), new HumidityStream());
	}

}
