FROM java:8
EXPOSE 8091

ADD /semantic-epa-actions-samples-0.0.1-SNAPSHOT.jar  /semantic-epa-actions-samples-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/semantic-epa-actions-samples-0.0.1-SNAPSHOT.jar"]
