FROM java:8
EXPOSE 8091

ADD ./de.fzi.cep.sepa/semantic-epa-actions-samples/0.0.1-SNAPSHOT/semantic-epa-actions-samples-0.0.1-SNAPSHOT.jar  /semantic-epa-actions-samples.jar

ENTRYPOINT ["java", "-jar", "/semantic-epa-actions-samples.jar"]
