package de.fzi.proasense.demonstrator.sources;

import java.util.Arrays;
import java.util.List;

import de.fzi.cep.sepa.desc.declarer.EventStreamDeclarer;
import de.fzi.cep.sepa.desc.declarer.SemanticEventProducerDeclarer;
import de.fzi.cep.sepa.model.impl.graph.SepDescription;
import de.fzi.proasense.demonstrator.streams.FlowRateSensorStream;

public class DemonstratorProducer implements SemanticEventProducerDeclarer {

	@Override
	public SepDescription declareModel() {
		return new SepDescription("source-demonstrator", "Demonstrator", "Provides streams generated by several sensors of the demonstrator");
	}

	@Override
	public List<EventStreamDeclarer> getEventStreams() {
		return Arrays.asList(new FlowRateSensorStream());
	}

}
