package de.fzi.proasense.hella.sources;

import java.util.Arrays;
import java.util.List;

import de.fzi.cep.sepa.desc.declarer.EventStreamDeclarer;
import de.fzi.cep.sepa.desc.declarer.SemanticEventProducerDeclarer;
import de.fzi.cep.sepa.model.impl.graph.SepDescription;
import de.fzi.proasense.hella.streams.DustParticleStream;
import de.fzi.proasense.hella.streams.HumidityStream;
import de.fzi.proasense.hella.streams.IrTemperatureStream;
import de.fzi.proasense.hella.streams.TemperatureStream;

public class EnvironmentalDataProducer implements SemanticEventProducerDeclarer {

	@Override
	public SepDescription declareModel() {
		SepDescription sep = new SepDescription("source-environmental", "Environmental Data", "Provides streams generated by environmental sensors");
		
		return sep;
	}

	@Override
	public List<EventStreamDeclarer> getEventStreams() {
		return Arrays.asList(new DustParticleStream(), new TemperatureStream(), new IrTemperatureStream(), new HumidityStream());
	}

}
