# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

debug: false

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: apachestreampipes
  pullPolicy: Always


# Enable DEBUG mode for the Backend
backend:
  # Override backend image name
  image: backend
  # Override the backend image tag - defaults to AppVersion
  tag: ""
  replicaCount: 1

  # Turn this up if using couchDB included with helm chart to allow time for couchDB to spin up
  # Turn down if couchdb is already deployed as it will only slow down the rollout
  initialDelaySeconds: 15

  failureThreshold: 30

  periodSeconds: 10

  containerPort: 8030

  service:
    port: 8030
    type: ClusterIP

  persistence:
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    annotations": {}
    storageClass: "standard"
    size: 1Gi

  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}
  podLabels: {}
  restartPolicy: "Always"

  resources:
    limits: {}
    requests: {}


# UI component configuration
ui:
  # Use this if you need to override the name of the ui container image
  image: ui

  # Override the backend image tag - defaults to AppVersion
  tag: ""

  replicaCount: 1

  initialDelaySeconds: 60

  failureThreshold: 30

  periodSeconds: 30

  containerPort: 8088

  service:
    port: 8088
    type: LoadBalancer
    resolverActive: true
    resolver: kube-dns.kube-system.svc.cluster.local

  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}
  podLabels: {}
  restartPolicy: "Always"

  resources:
    limits: {}
    requests: {}

extensions:
  # Use this if you need to override the name of the ui container image
  image: extensions-all-jvm

  # Override the backend image tag - defaults to AppVersion
  tag: ""

  replicaCount: 1

  initialDelaySeconds: 60

  failureThreshold: 30

  periodSeconds: 30

  containerPort: 8090

  service:
    port: 8090
    type: ClusterIP

  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0

  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}
  podLabels: {}
  restartPolicy: "Always"

  resources:
    limits: {}
    requests: {}

# Streampipes specific configuration
streampipes:
  # kafka, nats, pulsar
  broker:
    type: "kafka"
  admin:
    email: admin@streampipes.apache.org
    password: admin
  serviceUser:
    user: sp-service-client
    secret: ""
  encryption:
    passcode: ""
  secrets:
    existingSecret: ""
    adminPasswordSecretKey: sp-initial-admin-password
    clientSecretKey: sp-initial-client-secret
    encryptionPasscodeSecretKey: sp-encryption-password

# Network configuration
proxy: ""
noProxy: ""

# Message broker configuration
kafka:
  enabled: false

externalKafka:
  host: streampipes-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local
  port: 9092

nats:
  enabled: false

pulsar:
  enabled: false

# CouchDB is included into this release for convenience
# it is recommended to host it separately from this release
# set couchdb.enabled = false and configure externalCouchdb
couchdb:
  # If enabled you can override any couchdb settings from the couchdb helm chart
  enabled: false

  couchdbConfig:
    couchdb:
      uuid: decafbaddecafbaddecafbaddecafbad

  # DO NOT CHANGE - NOT CONFIGURED YET
  createAdminSecret: false

  adminUsername: admin

  adminPassword: admin

  adminHash: "1234"

  cookieAuthSecret: "1234"

  persistentVolume:
    enabled: false

    accessMode: ["ReadWriteOnce"]

    size: "10Gi"

    storageClass: "-"


# Required fields if couchdb.enabled = false
externalCouchdb:
  host: couchdb-svc-couchdb.couchdb.svc.cluster.local
  port: 5984

  # Required if existingSecret does not exist
  # Leave empty in existing secret does exist
  adminUsername: admin
  adminPassword: admin
  cookieAuthSecret: cookie
  erlangCookie: "1234"
  # Use an existing secret for the couchdb password
  existingSecret: ""
  # The key in the secret containing the couchdb user
  adminUsernameKey: adminUsername
  # The key in the secret containing the couchdb password
  adminPasswordKey: adminPassword
  # The key in the secret containing the cookieAuthSecret
  cookieAuthSecretKey: cookieAuthSecret
  # The key in the secret containing the erlangCookie
  erlangCookieSecretKey: erlangCookie

# Time series database configuration
influxdb:
  enabled: false
externalInfluxdb:
  host: influxdb.influxdb.svc.cluster.local
  port: 8086
  admin:
    password: ""
    token: ""
  existingSecret: influxdb-secret
  adminPasswordSecretKey: admin-user-password
  adminTokenSecretKey: admin-user-token

# Monitoring configuration
monitoring:
  enabled: false
  interval: 30s
  labels: {}

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  host: "demo.localdev.me"
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""



