package org.streampipes.pe.sources.demonstrator.sources;

import java.util.Arrays;
import java.util.List;

import org.streampipes.container.declarer.EventStreamDeclarer;
import org.streampipes.container.declarer.SemanticEventProducerDeclarer;
import org.streampipes.model.impl.graph.SepDescription;
import org.streampipes.pe.sources.demonstrator.config.DemonstratorVariables;
import org.streampipes.pe.sources.demonstrator.festo.streams.FestoContainerB101Stream;
import org.streampipes.pe.sources.demonstrator.festo.streams.FestoContainerB102Stream;
import org.streampipes.pe.sources.demonstrator.festo.streams.FestoFlowRateStream;
import org.streampipes.pe.sources.demonstrator.festo.streams.FestoPressureTankStream;

public class FestoProducer implements SemanticEventProducerDeclarer {

	@Override
	public SepDescription declareModel() {
		return new SepDescription("festo", "Festo",
				"Provides streams generated by the festo sensors of the demonstrator");
	}

	@Override
	public List<EventStreamDeclarer> getEventStreams() {
		return Arrays.asList(new FestoContainerB101Stream(DemonstratorVariables.FESTO_CONTAINERB101),
				new FestoContainerB102Stream(DemonstratorVariables.FESTO_CONTAINERB102),
				new FestoFlowRateStream(DemonstratorVariables.FESTO_FLOWRATE),
				new FestoPressureTankStream(DemonstratorVariables.FESTO_PRESSURE_TANK)
				);
	}
}
