package org.streampipes.pe.sources.demonstrator.sources;

import java.util.Arrays;
import java.util.List;

import org.streampipes.container.declarer.EventStreamDeclarer;
import org.streampipes.container.declarer.SemanticEventProducerDeclarer;
import org.streampipes.model.graph.DataSourceDescription;
import org.streampipes.pe.sources.demonstrator.config.DemonstratorVariables;
import org.streampipes.pe.sources.demonstrator.siemens.streams.SiemensFlowRateSensorStream;

public class SiemensProducer implements SemanticEventProducerDeclarer {

	@Override
	public DataSourceDescription declareModel() {
		return new DataSourceDescription("siemens", "Siemens",
				"Provides streams generated by the siemens sensors of the demonstrator");
	}

	@Override
	public List<EventStreamDeclarer> getEventStreams() {
		return Arrays.asList(new SiemensFlowRateSensorStream(DemonstratorVariables.SIENENS_FLOWRATESENSOR1),
				new SiemensFlowRateSensorStream(DemonstratorVariables.SIENENS_FLOWRATESENSOR2));
//				new SiemensFlowRateSensorStream(DemonstratorVariables.SIEMENS_LEVELSENSOR));
	}

}
