FROM java:8
EXPOSE 8089
EXPOSE 61616

ADD /semantic-epa-sources-samples-0.0.1-SNAPSHOT.jar  /semantic-epa-sources-samples-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/semantic-epa-sources-samples-0.0.1-SNAPSHOT.jar"]
