# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streampipes.extensions.fullname" . }}
  labels:
    {{- include "streampipes.extensions.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.extensions.replicaCount }}
  selector:
    matchLabels:
      {{- include "streampipes.extensions.selectorLabels" . | nindent 6 }}
  strategy: 
    {{- toYaml .Values.extensions.updateStrategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.extensions.podAnnotations }}
      annotations:
        random-annotation: {{ randAlphaNum 10 | lower }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "streampipes.extensions.selectorLabels" . | nindent 8 }}
        {{- if .Values.extensions.podLabels }}
        {{- toYaml .Values.extensions.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "streampipes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.extensions.securityContext | nindent 8 }}
      initContainers:
        - name: init-wait-backend
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 {{ include "streampipes.backend.fullname" .}} {{ .Values.backend.service.port }} && exit 0 || sleep 3; done; exit 1"]
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
          - {{ include "streampipes.extensions.fullname" . }}
      restartPolicy: {{ .Values.extensions.restartPolicy }}
      containers:
      - name: {{ include "streampipes.extensions.fullname" . }}
        image: {{ include "streampipes.extensions.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.extensions.containerPort }}
        env:
          {{- include "snippet.streampipes.extensions.env" . | nindent 12 }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.extensions.containerPort }}
          initialDelaySeconds: {{ .Values.extensions.initialDelaySeconds }}
          periodSeconds: {{ .Values.extensions.periodSeconds }}
          failureThreshold: {{ .Values.extensions.failureThreshold }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.extensions.containerPort }}
          initialDelaySeconds: {{ .Values.extensions.initialDelaySeconds }}
          periodSeconds: {{ .Values.extensions.periodSeconds }}
          failureThreshold: {{ .Values.extensions.failureThreshold }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.extensions.containerPort }}
          initialDelaySeconds: {{ .Values.extensions.initialDelaySeconds }}
          periodSeconds: {{ .Values.extensions.periodSeconds }}
          failureThreshold: {{ .Values.extensions.failureThreshold }}
  
