package de.fzi.cep.sepa.webapp.examples;

import java.util.ArrayList;
import java.util.List;

import de.fzi.cep.sepa.model.client.Domain;
import de.fzi.cep.sepa.model.client.SEPAClient;
import de.fzi.cep.sepa.model.client.SourceClient;
import de.fzi.cep.sepa.model.client.StreamClient;
import de.fzi.cep.sepa.model.client.examples.SEPAFactory;
import de.fzi.cep.sepa.model.client.examples.SourceFactory;
import de.fzi.cep.sepa.model.client.examples.StreamFactory;
import de.fzi.sepa.model.client.manager.SEPAManager;

public class DemoDataGenerator {

	public static void generateDemoData()
	{
		SEPAManager manager = SEPAManager.INSTANCE;
		
		//generate event sources
		//proasense
		List<SourceClient> sources = new ArrayList<SourceClient>();
		SourceClient ddm = SourceFactory.generateSourceMock("DDM", "produces events generated by the Derrick Drilling machine", createDomainList(Domain.DOMAIN_PROASENSE));
		SourceClient ibop = SourceFactory.generateSourceMock("IBOP", "internal blowout preventer", createDomainList(Domain.DOMAIN_PROASENSE));
		SourceClient weather = SourceFactory.generateSourceMock("Weather", "produces weather information at a given location", createDomainList(Domain.DOMAIN_PROASENSE, Domain.DOMAIN_PERSONAL_ASSISTANT));
		SourceClient drillBit = SourceFactory.generateSourceMock("drillBit", "produces events generated by the drill string", createDomainList(Domain.DOMAIN_PROASENSE));
		
		//personalassistant
		SourceClient mobilePhone = SourceFactory.generateSourceMock("Mobile Phone", "produces events generated by a mobile phone", createDomainList(Domain.DOMAIN_PERSONAL_ASSISTANT));
		SourceClient twitter = SourceFactory.generateSourceMock("Twitter", "produces tweets written by twitter users", createDomainList(Domain.DOMAIN_PERSONAL_ASSISTANT));
		
		
		sources.add(ddm);
		sources.add(ibop);
		sources.add(weather);
		sources.add(drillBit);
		sources.add(mobilePhone);
		sources.add(twitter);
		
		manager.setStoredSources(sources);
		
		
		//generate event producers
		List<StreamClient> seps = new ArrayList<StreamClient>();
		
		StreamClient speedShaft = StreamFactory.generateSEPMock("DDM Speed Shaft", "", ddm.getElementId());
		StreamClient torque = StreamFactory.generateSEPMock("DDM Torque", "", ddm.getElementId());
		StreamClient hookLoad = StreamFactory.generateSEPMock("DDM Hook Load", "", ddm.getElementId());
		StreamClient gearboxTemperature = StreamFactory.generateSEPMock("DDM Gearbox Temperature", "", ddm.getElementId());
		StreamClient ddmSwivelTemperature = StreamFactory.generateSEPMock("DDM Swivel Temperature", "", ddm.getElementId());
		
		StreamClient ibopStatus = StreamFactory.generateSEPMock("IBOP Status", "", ibop.getElementId());
		
		StreamClient ambientTemperature = StreamFactory.generateSEPMock("Ambient Temperature", "", weather.getElementId());
		StreamClient wind = StreamFactory.generateSEPMock("Wind conditions", "", weather.getElementId());
		
		StreamClient weightOnBit = StreamFactory.generateSEPMock("Weight On Bit", "", drillBit.getElementId());
		
		StreamClient battery = StreamFactory.generateSEPMock("Battery level", "", mobilePhone.getElementId());
		StreamClient calendar = StreamFactory.generateSEPMock("Calendar appointment scheduled", "", mobilePhone.getElementId());
		StreamClient location = StreamFactory.generateSEPMock("Location", "current location", mobilePhone.getElementId());
		StreamClient microphone = StreamFactory.generateSEPMock("Microphone", "publishes current sound level", mobilePhone.getElementId());
		StreamClient tweet = StreamFactory.generateSEPMock("Tweet", "", twitter.getElementId());
		StreamClient retweet = StreamFactory.generateSEPMock("Retweet", "", twitter.getElementId());
		
		
		seps.add(speedShaft);
		seps.add(torque);
		seps.add(hookLoad);
		seps.add(gearboxTemperature);
		seps.add(ddmSwivelTemperature);
		seps.add(ibopStatus);
		seps.add(ambientTemperature);
		seps.add(weightOnBit);
		seps.add(battery);
		seps.add(calendar);
		seps.add(location);
		seps.add(microphone);
		seps.add(tweet);
		seps.add(retweet);
		seps.add(wind);
		
		manager.setStoredSEPs(seps);
	
		
		//generate epas
		List<SEPAClient> sepas = new ArrayList<SEPAClient>();
		
		SEPAClient drillingStart = SEPAFactory.generateSEPAMock("Drilling Start", "Detects start of a drilling process", createDomainList(Domain.DOMAIN_PROASENSE));
		SEPAClient drillingStop = SEPAFactory.generateSEPAMock("Drilling Start", "Detects stop of a drilling process", createDomainList(Domain.DOMAIN_PROASENSE));
		SEPAClient coolingDownStart = SEPAFactory.generateSEPAMock("Cooling Down Start", "Detects start of cooling down process", createDomainList(Domain.DOMAIN_PROASENSE));
		SEPAClient coolingDownStop = SEPAFactory.generateSEPAMock("Cooling Down Stop", "Detects stop of a cooling down process", createDomainList(Domain.DOMAIN_PROASENSE));
		SEPAClient suddenIncreaseDecrease = SEPAFactory.generateSEPAMock("Drilling Start", "Detects the start of a drilling process", createDomainList(Domain.DOMAIN_PROASENSE));
		SEPAClient simpleTextFilter = SEPAFactory.generateSEPAMock("Filter", "Filter that operates on textual data", createDomainList(Domain.DOMAIN_PERSONAL_ASSISTANT));
		SEPAClient proximity = SEPAFactory.generateSEPAMock("Proximity", "Detects proximity between two location-based objects", createDomainList(Domain.DOMAIN_PERSONAL_ASSISTANT));
		SEPAClient sentiment = SEPAFactory.generateSEPAMock("Sentiment Detection", "calculates sentiment of textual data", createDomainList(Domain.DOMAIN_PERSONAL_ASSISTANT));
		
		sepas.add(drillingStart);
		sepas.add(drillingStop);
		sepas.add(coolingDownStart);
		sepas.add(coolingDownStop);
		sepas.add(suddenIncreaseDecrease);
		sepas.add(simpleTextFilter);
		sepas.add(proximity);
		sepas.add(sentiment);
		
		manager.setStoredSEPAs(sepas);
	
	}
	
	private static List<String> createDomainList(Domain...domains)
	{
		List<String> result = new ArrayList<String>();
		for(Domain domain : domains)
		{
			result.add(domain.toString());
		}
		return result;
	}

}

