package de.fzi.cep.sepa.webapp.examples;

import java.util.ArrayList;
import java.util.List;





import de.fzi.cep.sepa.model.SEPObjectFactory;
import de.fzi.cep.sepa.model.client.examples.SourceFactory;
import de.fzi.cep.sepa.model.impl.Domain;
import de.fzi.cep.sepa.model.impl.SEP;
import de.fzi.cep.sepa.storage.SEPAManager;



public class ModelDemoDataGenerator {

	public static void generateDemoData()
	{
		SEPAManager manager = SEPAManager.INSTANCE;
		
		List<SEP> seps = new ArrayList<SEP>();
		
		/*
		SEP ddm = SEPObjectFactory.createSEP("DDM", "produces events generated by the Derrick Drilling machine", createDomainList(Domain.DOMAIN_PROASENSE));
		SEP ibop = SEPObjectFactory.createSEP("IBOP", "internal blowout preventer", createDomainList(Domain.DOMAIN_PROASENSE));
		SEP weather = SEPObjectFactory.createSEP("Weather", "produces weather information at a given location", createDomainList(Domain.DOMAIN_PROASENSE, Domain.DOMAIN_PERSONAL_ASSISTANT));
		SEP drillBit = SEPObjectFactory.createSEP("drillBit", "produces events generated by the drill string", createDomainList(Domain.DOMAIN_PROASENSE));
		
		seps.add(ddm);
		seps.add(ibop);
		seps.add(weather);
		seps.add(drillBit);
		*/
		
		
	}
	
	private static List<Domain> createDomainList(Domain...domains)
	{
		List<Domain> result = new ArrayList<Domain>();
		for(Domain domain : domains)
		{
			result.add(domain);
		}
		return result;
	}
}
