name: Python Workflows
on:
  push:
    paths:
      - '**.py'
jobs:
  python-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install Python dependencies
        working-directory: ./streampipes-client-python
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e ".[dev]"

      - name: Run style & code checks
        working-directory: ./streampipes-client-python
        run: |
          make pre-commit
          make mypy
          make lint

  python-unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python v${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install Python dependencies
        working-directory: ./streampipes-client-python
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e ".[dev]"

      - name: Run unit-tests
        working-directory: ./streampipes-client-python
        run: |
          make unit-tests

  python-doc-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache Python doc dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-doc-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-doc-

      - name: Install Python dependencies
        working-directory: ./streampipes-client-python
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e ".[docs]"

      - name: Build MkDocs
        working-directory: ./streampipes-client-python
        run: |
          make doc