package de.fzi.proasense.demonstrator.sources;

import java.util.Arrays;
import java.util.List;

import de.fzi.cep.sepa.client.declarer.EventStreamDeclarer;
import de.fzi.cep.sepa.client.declarer.SemanticEventProducerDeclarer;
import de.fzi.cep.sepa.model.impl.graph.SepDescription;
import de.fzi.proasense.demonstrator.config.DemonstratorVariables;
import de.fzi.proasense.demonstrator.festo.streams.FestoContainerB101Stream;
import de.fzi.proasense.demonstrator.festo.streams.FestoContainerB102Stream;
import de.fzi.proasense.demonstrator.festo.streams.FestoFlowRateStream;
import de.fzi.proasense.demonstrator.festo.streams.FestoPressureTankStream;

public class FestoProducer implements SemanticEventProducerDeclarer {

	@Override
	public SepDescription declareModel() {
		return new SepDescription("festo", "Festo",
				"Provides streams generated by the festo sensors of the demonstrator");
	}

	@Override
	public List<EventStreamDeclarer> getEventStreams() {
		return Arrays.asList(new FestoContainerB101Stream(DemonstratorVariables.FESTO_CONTAINERB101),
				new FestoContainerB102Stream(DemonstratorVariables.FESTO_CONTAINERB102),
				new FestoFlowRateStream(DemonstratorVariables.FESTO_FLOWRATE),
				new FestoPressureTankStream(DemonstratorVariables.FESTO_PRESSURE_TANK)
				);
	}
}
